AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: envios

Globals:
  Function:
    Timeout: 6

Resources:
  Envios:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        CreateEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        ListEnviosPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        UpdateEnvio:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put